* System Configuration

  Everything needed to build my NixOS system for play and Windows for work.

** Folder Structure

The following is 1 level deep directory structure generated using ~tree -L 1 -d~.

#+begin_src
.
├── config
├── config-backups
├── emacs
├── keyboard-firmware
├── machines
├── nix
├── pia
└── xmonad
#+end_src

*** config

Config files used in NixOS that are symlinked to ~/.config/~ and managed with
[[https://github.com/rycee/home-manager][home manager]].

*** config-backups

Miscellaneous configuration files that I'm backing up and are not deployed
automatically.

*** emacs

My emacs configuration code. See its [[file:emacs/readme.org][readme]] for more information.

*** keyboard-firmware

Holds my keyboard firmware code managed by Nix and the the
[[file:keyboard-firmware/readme.org][readme]] that goes into depth on my key
layout and customized Evil / Vim keybindings.

*** machines

Machine / host specific configuration files.

*** nix

This is a sources directory generated by [[https://github.com/niv][niv]] that
holds pinned nix sources (at least until I switch to Nix Flakes).

*** xmonad

My Xmonad configuration code which is symlinked by home-manager.
