* NixOS system configuration

Everything needed to build my NixOS system.

I run an [[https://github.com/nix-community/impermanence][impermanent]] setup with tmpfs as root, flakes, LUKS encryption. Check
out [[https://willbush.dev/blog/impermanent-nixos/][this blog]] post I made if you're interested.

* Folder Structure

The following is 1 level deep directory structure generated using ~tree -L 1 -d~.

#+begin_src
.
├── configs
├── hosts
├── modules
├── profiles
├── secrets
└── users
#+end_src

** configs

A sort of catch all for config / non-nix code.

Some are simply configuration files that are symlinked to ~/.config/~ and managed
with [[https://github.com/rycee/home-manager][home manager]].

*** keyboard firmware

Keyboard firmware code managed by Nix and the [[file:configs/keyboard-firmware/readme.org][readme]] that goes into depth on my
key layout and customized Evil / Vim keybindings.

*** emacs / nvim

My emacs configuration code. See its [[file:configs/emacs/readme.org][readme]] for more information.

I typically only use Vim if Emacs is not available for some reason. In the
~init.vim~ file there are just the most important key bindings in my [[configs/keyboard-firmware/readme.org][customized
Evil / Vim keybindings]]

** hosts

host specific configuration files.

** modules, profiles, and users

similar to and inspired by: https://devos.divnix.com/index.html

** secrets

A place for me to store encrypted secrets using [[https://github.com/AGWA/git-crypt][git-crypt]].

* License

Dual licensed under either:

- Apache License, Version 2.0 ([[http://www.apache.org/licenses/LICENSE-2.0][LICENSE-APACHE]])

- MIT license ([[http://opensource.org/licenses/MIT][LICENSE-MIT]])

at your option.
