# Generated by /home/will/system/nixos/pia/gen-pia-server-list.sh

[
  { id = "PIA - US California";
    uuid = "24b8bd23-8202-447a-99e6-5ee625fe3aa2";
    remote = "us-california.privateinternetaccess.com";
  }
  { id = "PIA - US East";
    uuid = "0972e17c-a716-4f1e-96a0-f981ad010b76";
    remote = "us-east.privateinternetaccess.com";
  }
  { id = "PIA - US Chicago";
    uuid = "630a0508-f3c2-4b37-8edc-3aabffe00f5f";
    remote = "us-chicago.privateinternetaccess.com";
  }
  { id = "PIA - US Dallas";
    uuid = "f2c3b998-acc5-4bcb-8359-87b6b0251a75";
    remote = "us-dal.privateinternetaccess.com";
  }
  { id = "PIA - US Florida";
    uuid = "ecba004e-597c-4926-a6c6-eccfdcc9a364";
    remote = "us-florida.privateinternetaccess.com";
  }
  { id = "PIA - US Seattle";
    uuid = "9f7e5205-19fd-4433-8ae9-fd223893e117";
    remote = "us-sea.privateinternetaccess.com";
  }
  { id = "PIA - US West";
    uuid = "7405be57-c635-45cc-ab7a-ef2341563a77";
    remote = "us-west.privateinternetaccess.com";
  }
  { id = "PIA - US Silicon Valley";
    uuid = "9ebb7f79-3ffe-406b-9bec-40897a3f4fb6";
    remote = "us-siliconvalley.privateinternetaccess.com";
  }
  { id = "PIA - US New York City";
    uuid = "a6a4b961-18e1-43fc-a72b-fb43ba37f00e";
    remote = "us-nyc.privateinternetaccess.com";
  }
  { id = "PIA - US Washington DC";
    uuid = "ea1245fa-31ab-4636-a71f-29f97de46233";
    remote = "us-washingtondc.privateinternetaccess.com";
  }
  { id = "PIA - US Atlanta";
    uuid = "8b299956-87d3-4d52-9e20-db1ea7feaff5";
    remote = "us-atlanta.privateinternetaccess.com";
  }
  { id = "PIA - US Las Vegas";
    uuid = "bd08452e-236a-40cb-8168-b481990cbf25";
    remote = "us-lasvegas.privateinternetaccess.com";
  }
  { id = "PIA - US Houston";
    uuid = "bde7bb95-2cb0-4891-a27a-ef9f9c59bbba";
    remote = "us-houston.privateinternetaccess.com";
  }
  { id = "PIA - US Denver";
    uuid = "79d53b04-9086-448b-a6fe-3bdf40058dcf";
    remote = "us-denver.privateinternetaccess.com";
  }
  { id = "PIA - UK London";
    uuid = "c17baf8a-6ceb-4b47-8762-4db9e6c2eee4";
    remote = "uk-london.privateinternetaccess.com";
  }
  { id = "PIA - UK Southampton";
    uuid = "3dffe018-8922-4701-b37f-c8e87db6db8a";
    remote = "uk-southampton.privateinternetaccess.com";
  }
  { id = "PIA - UK Manchester";
    uuid = "04aecb91-0e06-4981-930a-be403f5ebfc2";
    remote = "uk-manchester.privateinternetaccess.com";
  }
  { id = "PIA - CA Ontario";
    uuid = "aead86bd-060d-42a9-b480-25635dbe2ffd";
    remote = "ca-ontario.privateinternetaccess.com";
  }
  { id = "PIA - CA Toronto";
    uuid = "480be008-d25d-400c-b254-5690a4049954";
    remote = "ca-toronto.privateinternetaccess.com";
  }
  { id = "PIA - CA Montreal";
    uuid = "4bee2c05-9999-4da9-a5bb-14b0859606b6";
    remote = "ca-montreal.privateinternetaccess.com";
  }
  { id = "PIA - CA Vancouver";
    uuid = "26950ebf-2375-40e1-9469-6d045a65cf4f";
    remote = "ca-vancouver.privateinternetaccess.com";
  }
  { id = "PIA - AU Sydney";
    uuid = "0212e29b-7e96-42b5-a0fe-8e25db56c9a4";
    remote = "au-sydney.privateinternetaccess.com";
  }
  { id = "PIA - AU Melbourne";
    uuid = "82541464-d68c-4ead-ab95-de0c7a3e0696";
    remote = "au-melbourne.privateinternetaccess.com";
  }
  { id = "PIA - AU Perth";
    uuid = "570b48ea-1657-478e-90cb-6202c024d10b";
    remote = "au-perth.privateinternetaccess.com";
  }
  { id = "PIA - DE Berlin";
    uuid = "cdd3be6f-38c5-4058-8701-60f875600cb1";
    remote = "de-berlin.privateinternetaccess.com";
  }
  { id = "PIA - DE Frankfurt";
    uuid = "335dbd0b-4a27-4c2e-ac34-3141817aa70c";
    remote = "de-frankfurt.privateinternetaccess.com";
  }
  { id = "PIA - New Zealand";
    uuid = "440d4446-24ff-4852-a760-bd13e1cad9e1";
    remote = "nz.privateinternetaccess.com";
  }
  { id = "PIA - Albania";
    uuid = "69d3bf5f-9832-42de-ad1a-2619cbf44bde";
    remote = "albania.privateinternetaccess.com";
  }
  { id = "PIA - Netherlands";
    uuid = "f248db23-1ac4-4d73-be74-9569b8eeee92";
    remote = "nl.privateinternetaccess.com";
  }
  { id = "PIA - Iceland";
    uuid = "3b4d06e0-c1c3-4a0a-bcf9-5358db1c0cce";
    remote = "is.privateinternetaccess.com";
  }
  { id = "PIA - Sweden";
    uuid = "c93e9210-ddb6-45ba-8bbd-8702edc8c689";
    remote = "sweden.privateinternetaccess.com";
  }
  { id = "PIA - Norway";
    uuid = "d25c6b71-ee8b-4685-aabb-810644eff79f";
    remote = "no.privateinternetaccess.com";
  }
  { id = "PIA - Denmark";
    uuid = "e387f1f5-003a-4309-9766-089217936b1c";
    remote = "denmark.privateinternetaccess.com";
  }
  { id = "PIA - Finland";
    uuid = "eac834b6-b6fc-4d87-85f4-720ed5d7c20c";
    remote = "fi.privateinternetaccess.com";
  }
  { id = "PIA - Switzerland";
    uuid = "7b1b2223-877d-4c5a-a203-4723ed8e13ac";
    remote = "swiss.privateinternetaccess.com";
  }
  { id = "PIA - France";
    uuid = "bb542b23-8820-4a1e-9813-8fb07621bd29";
    remote = "france.privateinternetaccess.com";
  }
  { id = "PIA - Belgium";
    uuid = "a7fc5303-43c7-4ead-9411-03b1ef646992";
    remote = "belgium.privateinternetaccess.com";
  }
  { id = "PIA - Austria";
    uuid = "e35cf1d7-c38b-44f3-87cf-665a6c5eff2c";
    remote = "austria.privateinternetaccess.com";
  }
  { id = "PIA - Czech Republic";
    uuid = "64f8db6f-1b79-42e2-8b27-068bfe0a7511";
    remote = "czech.privateinternetaccess.com";
  }
  { id = "PIA - Luxembourg";
    uuid = "5b232867-9be1-4d7a-841e-72e3f140b869";
    remote = "lu.privateinternetaccess.com";
  }
  { id = "PIA - Ireland";
    uuid = "c5a6546b-806b-4f14-8c7b-58c37347b62b";
    remote = "ireland.privateinternetaccess.com";
  }
  { id = "PIA - Italy";
    uuid = "35336dea-f382-475e-a4be-6f8692735ddb";
    remote = "italy.privateinternetaccess.com";
  }
  { id = "PIA - Portugal";
    uuid = "bc81df62-8772-44b8-ab01-ccbcfe17a151";
    remote = "pt.privateinternetaccess.com";
  }
  { id = "PIA - Spain";
    uuid = "70dfcf0a-8918-4025-a0d2-b6eb00c5c2ca";
    remote = "spain.privateinternetaccess.com";
  }
  { id = "PIA - Moldova";
    uuid = "1aa49f6f-e774-4257-bd74-60f084d66a55";
    remote = "md.privateinternetaccess.com";
  }
  { id = "PIA - Romania";
    uuid = "49ec5e0f-3cb4-41d4-8320-27cde0198772";
    remote = "ro.privateinternetaccess.com";
  }
  { id = "PIA - Bulgaria";
    uuid = "df8ef044-9fa8-4fce-93ea-ef872afe8d3d";
    remote = "bg.privateinternetaccess.com";
  }
  { id = "PIA - Serbia";
    uuid = "55c9cac1-3c96-47ea-b81d-8c96f2741792";
    remote = "rs.privateinternetaccess.com";
  }
  { id = "PIA - Latvia";
    uuid = "2c4c51e6-24e3-4fc7-b75f-1a864d1193a4";
    remote = "lv.privateinternetaccess.com";
  }
  { id = "PIA - Estonia";
    uuid = "7cee7c65-1213-4b16-b537-7645bb56fa00";
    remote = "ee.privateinternetaccess.com";
  }
  { id = "PIA - Lithuania";
    uuid = "5aacb83f-55de-4079-b218-cde070a86066";
    remote = "lt.privateinternetaccess.com";
  }
  { id = "PIA - Slovakia";
    uuid = "ed280643-3ea4-4366-b798-dc8bb198d675";
    remote = "sk.privateinternetaccess.com";
  }
  { id = "PIA - Hungary";
    uuid = "2ddc7170-23b5-44a6-9177-c237ccf05121";
    remote = "hungary.privateinternetaccess.com";
  }
  { id = "PIA - Poland";
    uuid = "d7ece3ec-f6b2-4893-bef1-4cf39bc64cad";
    remote = "poland.privateinternetaccess.com";
  }
  { id = "PIA - Greece";
    uuid = "a87610fd-fba5-4529-b53e-7c9e26179e1f";
    remote = "gr.privateinternetaccess.com";
  }
  { id = "PIA - Bosnia and Herzegovina";
    uuid = "8c5eeb3c-6582-446c-8d81-c1c7abf55e2b";
    remote = "ba.privateinternetaccess.com";
  }
  { id = "PIA - Ukraine";
    uuid = "19d51aaa-eddf-4875-8c7e-f5dd6d9cfe7c";
    remote = "ua.privateinternetaccess.com";
  }
  { id = "PIA - North Macedonia";
    uuid = "e3e98a27-23d1-4b23-9d97-3807204b94ee";
    remote = "mk.privateinternetaccess.com";
  }
  { id = "PIA - Turkey";
    uuid = "b0f7b9b9-2739-4614-a082-8c4687471764";
    remote = "tr.privateinternetaccess.com";
  }
  { id = "PIA - UAE";
    uuid = "ad02317e-fee5-43af-b03d-9161bef27af3";
    remote = "ae.privateinternetaccess.com";
  }
  { id = "PIA - Singapore";
    uuid = "3b42b7d5-1172-4f5b-8818-1b3d4f88f4ee";
    remote = "sg.privateinternetaccess.com";
  }
  { id = "PIA - Japan";
    uuid = "42fc6502-f90b-4446-bc93-415b41dba1a8";
    remote = "jp.privateinternetaccess.com";
  }
  { id = "PIA - Israel";
    uuid = "57bc5d10-4b5e-4013-a219-1d0d6ea73dda";
    remote = "israel.privateinternetaccess.com";
  }
  { id = "PIA - Argentina";
    uuid = "3035e6d5-8a34-4a1f-87d2-7429b0987f6f";
    remote = "ar.privateinternetaccess.com";
  }
  { id = "PIA - India";
    uuid = "dfd38b92-bcfe-4c4c-b4d8-6eb28543c975";
    remote = "in.privateinternetaccess.com";
  }
  { id = "PIA - South Africa";
    uuid = "81056c82-3f65-4974-a8b3-081b5295722c";
    remote = "za.privateinternetaccess.com";
  }
]
