# Generated by /home/will/system/nixos/pia/gen-pia-server-list.sh

[
  { id = "PIA - US California";
    uuid = "c8aee76f-d78c-4bf7-a43a-ee0151cf225c";
    remote = "us-california.privateinternetaccess.com";
  }
  { id = "PIA - US East";
    uuid = "a93302c4-fcc8-454e-a9b7-7e65c15bd8e7";
    remote = "us-east.privateinternetaccess.com";
  }
  { id = "PIA - US Chicago";
    uuid = "bf33af6b-640c-4e92-9b0a-9006681915e0";
    remote = "us-chicago.privateinternetaccess.com";
  }
  { id = "PIA - US Texas";
    uuid = "c9bef1c5-be88-4083-9cea-9c8988c6493f";
    remote = "us-texas.privateinternetaccess.com";
  }
  { id = "PIA - US Florida";
    uuid = "21f7efc2-5946-42bd-a2ff-d9a87d9cac97";
    remote = "us-florida.privateinternetaccess.com";
  }
  { id = "PIA - US Seattle";
    uuid = "ac906c0c-b5e4-45e9-98cc-74f9d6c9b685";
    remote = "us-seattle.privateinternetaccess.com";
  }
  { id = "PIA - US West";
    uuid = "fe9b98c7-bd63-475f-a221-d61460564ee1";
    remote = "us-west.privateinternetaccess.com";
  }
  { id = "PIA - US Silicon Valley";
    uuid = "d8b8ce87-dfc4-4d61-8bc6-d8396c4f6be6";
    remote = "us-siliconvalley.privateinternetaccess.com";
  }
  { id = "PIA - US New York City";
    uuid = "2e0d681c-961e-4ff0-869b-3b29a068e974";
    remote = "us-newyorkcity.privateinternetaccess.com";
  }
  { id = "PIA - US Washington DC";
    uuid = "daa31bea-b28d-431f-bde9-7f61ceed9be5";
    remote = "us-washingtondc.privateinternetaccess.com";
  }
  { id = "PIA - US Atlanta";
    uuid = "d82d7fad-61e8-4335-9eb0-d2cb58fc8051";
    remote = "us-atlanta.privateinternetaccess.com";
  }
  { id = "PIA - US Las Vegas";
    uuid = "ba040063-4b25-4c02-83ba-96718aee8a33";
    remote = "us-lasvegas.privateinternetaccess.com";
  }
  { id = "PIA - US Houston";
    uuid = "4860614c-2ef6-4cf7-b665-8c96be08c991";
    remote = "us-houston.privateinternetaccess.com";
  }
  { id = "PIA - US Denver";
    uuid = "ddf2de0c-c95b-464d-9d3e-81682ba8cced";
    remote = "us-denver.privateinternetaccess.com";
  }
  { id = "PIA - UK London";
    uuid = "6f349bf1-2a72-4b9c-b7b7-99e2061a232d";
    remote = "uk-london.privateinternetaccess.com";
  }
  { id = "PIA - UK Southampton";
    uuid = "d7cb98a4-f279-4c5e-ab09-37afe4403a9e";
    remote = "uk-southampton.privateinternetaccess.com";
  }
  { id = "PIA - UK Manchester";
    uuid = "cedcca71-dc5a-4cbb-b659-8032b8fe2f87";
    remote = "uk-manchester.privateinternetaccess.com";
  }
  { id = "PIA - CA Toronto";
    uuid = "9cf00d37-c225-4c68-89f7-2f7eaff12454";
    remote = "ca-toronto.privateinternetaccess.com";
  }
  { id = "PIA - CA Montreal";
    uuid = "78bcd0d8-2a6b-46b5-9659-13a7c4d9bf19";
    remote = "ca-montreal.privateinternetaccess.com";
  }
  { id = "PIA - CA Vancouver";
    uuid = "b04b1737-f230-4c21-862b-912caf5e9ddd";
    remote = "ca-vancouver.privateinternetaccess.com";
  }
  { id = "PIA - AU Sydney";
    uuid = "0d98a6d3-e2f9-479a-b392-e1d93221cec3";
    remote = "au-sydney.privateinternetaccess.com";
  }
  { id = "PIA - AU Melbourne";
    uuid = "ada100c2-971a-4fd3-a5fa-3edac924cf01";
    remote = "au-melbourne.privateinternetaccess.com";
  }
  { id = "PIA - AU Perth";
    uuid = "324f3c73-f0f2-4275-9618-b28eb3ab59bc";
    remote = "au-perth.privateinternetaccess.com";
  }
  { id = "PIA - DE Berlin";
    uuid = "9283cce6-944f-4a87-9c5f-4cabf2388fa4";
    remote = "de-berlin.privateinternetaccess.com";
  }
  { id = "PIA - DE Frankfurt";
    uuid = "e0967d3d-9c98-403d-82d5-83e3580c1d65";
    remote = "de-frankfurt.privateinternetaccess.com";
  }
  { id = "PIA - New Zealand";
    uuid = "db7bd426-34fa-454b-89ae-f0736d5007b9";
    remote = "nz.privateinternetaccess.com";
  }
  { id = "PIA - Netherlands";
    uuid = "a3fdbc69-3032-4d43-8a2c-61719ed35c03";
    remote = "nl.privateinternetaccess.com";
  }
  { id = "PIA - Sweden";
    uuid = "e1d50013-1eeb-4608-b140-45730f01f250";
    remote = "sweden.privateinternetaccess.com";
  }
  { id = "PIA - Norway";
    uuid = "cecd2b78-db91-4161-bf75-9c16d4cdb711";
    remote = "no.privateinternetaccess.com";
  }
  { id = "PIA - Denmark";
    uuid = "2b841927-5a09-4942-bec0-edb92d06cbdb";
    remote = "denmark.privateinternetaccess.com";
  }
  { id = "PIA - Finland";
    uuid = "1dfd6f31-4c09-4498-82e4-82e181d5af13";
    remote = "fi.privateinternetaccess.com";
  }
  { id = "PIA - Switzerland";
    uuid = "7c3cd23e-6106-4754-9a8f-5166e69e42c8";
    remote = "swiss.privateinternetaccess.com";
  }
  { id = "PIA - France";
    uuid = "46f706ce-d891-4bf1-8e59-a0249390f0e3";
    remote = "france.privateinternetaccess.com";
  }
  { id = "PIA - Belgium";
    uuid = "283cf6d2-8796-40f0-a291-a26cdc5f44c5";
    remote = "belgium.privateinternetaccess.com";
  }
  { id = "PIA - Austria";
    uuid = "8221d1d4-148a-4b67-89d2-851823d20646";
    remote = "austria.privateinternetaccess.com";
  }
  { id = "PIA - Czech Republic";
    uuid = "a93ddb62-3be4-4bfc-8082-8abf0dc5e0b4";
    remote = "czech.privateinternetaccess.com";
  }
  { id = "PIA - Luxembourg";
    uuid = "7c5ffd3d-5093-4251-b239-c803ebc9260e";
    remote = "lu.privateinternetaccess.com";
  }
  { id = "PIA - Ireland";
    uuid = "7f2df69d-5faf-4f22-b59a-3a5e8f0e86be";
    remote = "ireland.privateinternetaccess.com";
  }
  { id = "PIA - Italy";
    uuid = "163fe8c8-a40f-4129-b670-c8c025f54a52";
    remote = "italy.privateinternetaccess.com";
  }
  { id = "PIA - Spain";
    uuid = "c1bccad9-644a-4870-b023-10eb89582642";
    remote = "spain.privateinternetaccess.com";
  }
  { id = "PIA - Romania";
    uuid = "86217f1a-b579-4cac-9083-6a4bafbbaa6a";
    remote = "ro.privateinternetaccess.com";
  }
  { id = "PIA - Hungary";
    uuid = "4b3541cc-8761-46bd-881c-675846419693";
    remote = "hungary.privateinternetaccess.com";
  }
  { id = "PIA - Poland";
    uuid = "c1e99ff3-a22a-4bf8-9a7c-96da535f15a7";
    remote = "poland.privateinternetaccess.com";
  }
  { id = "PIA - UAE";
    uuid = "443e0f0e-a4ce-4030-a43f-40d5f8f62d3a";
    remote = "ae.privateinternetaccess.com";
  }
  { id = "PIA - Hong Kong";
    uuid = "f1867b98-7cda-4f23-a7e9-4ef8ffb28002";
    remote = "hk.privateinternetaccess.com";
  }
  { id = "PIA - Singapore";
    uuid = "03337d4b-63d2-4c68-aa56-37a877af849f";
    remote = "sg.privateinternetaccess.com";
  }
  { id = "PIA - Japan";
    uuid = "bfc9af3d-91ec-40d6-bdbb-8c07bdd2d42a";
    remote = "japan.privateinternetaccess.com";
  }
  { id = "PIA - Israel";
    uuid = "64c6fa59-1dd3-4092-95f7-6048aa963248";
    remote = "israel.privateinternetaccess.com";
  }
  { id = "PIA - Mexico";
    uuid = "fb37bf93-84dd-4f3f-9758-5e345a0b5c4f";
    remote = "mexico.privateinternetaccess.com";
  }
  { id = "PIA - Brazil";
    uuid = "2da9f9cf-4fdb-4bdc-bced-d05a1efad836";
    remote = "brazil.privateinternetaccess.com";
  }
  { id = "PIA - India";
    uuid = "8e4406b5-8bc3-49f9-ba7b-a90538193ed0";
    remote = "in.privateinternetaccess.com";
  }
  { id = "PIA - South Africa";
    uuid = "5533c9a7-7c50-4f94-88e4-adac53b6659a";
    remote = "za.privateinternetaccess.com";
  }
]
