* Evil Begins
Are you a Vim user? Tempted to try Emacs? This is for you.

** About

I'm a Vim user. My two favourite implementations of Vim are:

1. Vim. (Most operating systems.)
2. Evil. (Emacs OS only.)

If you want to try option 2, (for reasons including, but not limited
to, Clojure awesomeness), this should give you a good starting
point. Broadly speaking, it gives you Vim-style editing in an Emacs
environment.

** Getting Started.

The "try before you buy" setup is:

#+BEGIN_SRC sh
$ git clone https://github.com/krisajenkins/EvilBegins.git
$ cd EvilBegins

$ ( HOME=`pwd` emacs )

# Alternatively OSX Users might prefer:
$ ( HOME=`pwd` open /Applications/Emacs.app/ )
#+END_SRC

That'll let you give it a spin without making any changes outside the
cloned directory.
(Note that the first time it runs, it'll download a truckload of
dependencies, so you'll need to be patient.)

Play around, and if you like what you see then:

#+BEGIN_SRC sh
$ cp ./.emacs ~/
#+END_SRC

...to make it your default =emacs= setup.

** Feedback

This project will never be exactly like Vim, and it's not supposed to
be. Emacs is a different beast. Rather, the aim is to allow you to
carry your muscle-memory across to a new environment.

If you try this project and /immediately/ miss Feature X, please let me
know. It should probably be in here, especially if it's a built-in
feature of Vim.

If you try this project and a week later miss Feature X, please let me
know anyway - I'd like to help - but it probably means you're ready to
dive deeper into Emacs.

** Credit

This all stands on the glorious shoulders of [[https://gitorious.org/evil/pages/Home][evil-mode]]. All I'm really
doing is packaging it up in an easy-to-get-started fashion.
