name: Dead code analysis
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron:
        "0 0 1 * *" # It runs at midnight (0 hour 0 minute) of the 1st day
        # of every month.

jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
